[package]
name = "lc3-emulator"
version = "0.1.0"
edition = "2024"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
# cargo = "warn"

[dependencies]
thiserror = "2.0"

[dev-dependencies]
googletest = "0.14"