[package]
name = "lc3-emulator"
version = "0.1.0"
edition = "2024"
# https://releases.rs/#rust-versions
# at least half a year, 1.87 from 15 May, 2025
rust-version = "1.87"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
# cargo = "warn"

[dependencies]
thiserror = "2.0"

[dev-dependencies]
googletest = "0.14"
