name: Build (main)
permissions:
  contents: read
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    name: Build, Test and verify with rustfmt as well as Clippy
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      # https://github.com/actions-rust-lang/setup-rust-toolchain
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Clippy
        run: cargo clippy
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
  msrv:
    name: Verify Minimum Stable Rust Version (MSRV) guarantee
    runs-on: ubuntu-latest
    outputs:
      msrv-version: ${{ steps.msrv-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - uses: cargo-bins/cargo-binstall@main
      - run: |
          cargo binstall --no-confirm cargo-msrv --locked
          cargo-msrv verify
      # - id: msrv-version
      #   run: |
      #     version=$(cargo-msrv show --output-format minimal)
      #     echo "version=$version" >> "$GITHUB_OUTPUT"
  # call-generate-readme:
  #   permissions:
  #     contents: write
  #   needs: msrv
  #   uses: ./.github/workflows/generate-readme.yml
  #   with:
  #     msrv: ${{ needs.msrv.outputs.msrv-version }}
