name: Build (main)
permissions:
  contents: read
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      build-profile:
        description: Cargo profile to use for build command
        default: release
        required: true
        type: choice
        options:
          - dev
          - release
      oses:
        description: The OSes to build on
        default: '[ "windows-latest", "macos-latest", "ubuntu-latest" ]'
        required: true
        type: choice
        options:
          - '[ "ubuntu-latest" ]'
          - '[ "windows-latest", "macos-latest" ]'
          - '[ "windows-latest", "macos-latest", "ubuntu-latest" ]'
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.oses == '' && '["ubuntu-latest"]' || inputs.oses) }}
    name: Build, Test and verify with rustfmt as well as Clippy
    env:
      BUILD_PROFILE: ${{ inputs.build-profile == '' && 'dev' || inputs.build-profile }}
      EXECUTABLE_DIR: target/${{ ((inputs.build-profile == '' ) || (inputs.build-profile == 'dev')) && 'debug' || 'release' }}
      EXECUTABLE_NAME: ${{ github.event.repository.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      # https://github.com/actions-rust-lang/setup-rust-toolchain
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test
      - name: Build
        run: cargo build --profile ${{ env.BUILD_PROFILE }}
      - name: Upload Artifact
        env:
          EXECUTABLE_SUFFIX: ${{ runner.os == 'Windows' && '.exe' || '' }}
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.EXECUTABLE_NAME }}-${{matrix.os}}${{ env.EXECUTABLE_SUFFIX }}
          path: ${{ env.EXECUTABLE_DIR }}/${{ env.EXECUTABLE_NAME }}${{ env.EXECUTABLE_SUFFIX }}
          if-no-files-found: error
  msrv:
    name: Verify Minimum Stable Rust Version (MSRV) guarantee
    runs-on: ubuntu-latest
    # outputs:
    #   msrv-version: ${{ steps.msrv-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - uses: cargo-bins/cargo-binstall@main
      - run: |
          cargo binstall --no-confirm cargo-msrv --locked
          cargo-msrv verify
      # - id: msrv-version
      #   run: |
      #     version=$(cargo-msrv show --output-format minimal)
      #     echo "version=$version" >> "$GITHUB_OUTPUT"
  # call-generate-readme:
  #   permissions:
  #     contents: write
  #   needs: msrv
  #   uses: ./.github/workflows/generate-readme.yml
  #   with:
  #     msrv: ${{ needs.msrv.outputs.msrv-version }}
