name: Build (main) - workflow_call
env:
  CARGO_TERM_COLOR: always
  UBUNTU_ARM_VERSION: 24.04
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      build-profile:
        description: Cargo profile to use for build command
        required: true
        type: string
      oses:
        description: The OSes to build on
        required: true
        type: string
    outputs:
      run-id:
        value: ${{ github.run_id }}
        description: run id which can be used for downloading artifacts uploaded by this workflow
jobs:
  replace-ubuntu-arm-version:
    # No latest available for ubuntu arm, see https://github.com/orgs/community/discussions/148648#discussioncomment-11858287
    runs-on: ubuntu-latest
    outputs:
      OSES: ${{ steps.os-arr-gen.outputs.oses }}
    steps:
      - id: os-arr-gen
        env:
          OSES_TO_BUILD_ON: ${{ format(inputs.oses, env.UBUNTU_ARM_VERSION ) }}
        run: |
          echo "oses=$OSES_TO_BUILD_ON" >> "$GITHUB_OUTPUT"
  build:
    needs: replace-ubuntu-arm-version
    strategy:
      matrix:
        os: ${{ fromJSON(needs.replace-ubuntu-arm-version.outputs.OSES) }}
    name: Build, Test and verify with rustfmt as well as Clippy
    env:
      DEBUG_OR_RELEASE: ${{ ((inputs.build-profile == '' ) || (inputs.build-profile == 'dev')) && 'debug' || 'release' }}
      EXECUTABLE_NAME: ${{ github.event.repository.name }}
      # NEEDS_CONTEXT: ${{ toJSON(needs) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      # https://github.com/actions-rust-lang/setup-rust-toolchain
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test
      - name: Build
        run: cargo build --profile ${{ inputs.build-profile }}
      - name: Rename Artifact
        id: rename-artifact
        env:
          EXECUTABLE_SUFFIX: ${{ runner.os == 'Windows' && '.exe' || '' }}
        run: mv target/${{ env.DEBUG_OR_RELEASE }}/${{ env.EXECUTABLE_NAME }}${{ env.EXECUTABLE_SUFFIX }} target/${{ env.EXECUTABLE_NAME }}-${{runner.os}}-${{ runner.arch }}-${{ env.DEBUG_OR_RELEASE }}${{ env.EXECUTABLE_SUFFIX }}
      - name: Upload Artifact
        id: upload-artifact
        env:
          EXECUTABLE_SUFFIX: ${{ runner.os == 'Windows' && '.exe' || '' }}
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.EXECUTABLE_NAME }}-${{runner.os}}-${{ runner.arch }}-${{ env.DEBUG_OR_RELEASE }}${{ env.EXECUTABLE_SUFFIX }}
          path: target/${{ env.EXECUTABLE_NAME }}-${{runner.os}}-${{ runner.arch }}-${{ env.DEBUG_OR_RELEASE }}${{ env.EXECUTABLE_SUFFIX }}
          if-no-files-found: error
  msrv:
    name: Verify Minimum Stable Rust Version (MSRV) guarantee
    runs-on: ubuntu-latest
    # outputs:
    #   msrv-version: ${{ steps.msrv-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - uses: cargo-bins/cargo-binstall@main
      - run: |
          cargo binstall --no-confirm cargo-msrv --locked
          cargo-msrv verify
      # - id: msrv-version
      #   run: |
      #     version=$(cargo-msrv show --output-format minimal)
      #     echo "version=$version" >> "$GITHUB_OUTPUT"
  # call-generate-readme:
  #   permissions:
  #     contents: write
  #   needs: msrv
  #   uses: ./.github/workflows/generate-readme.yml
  #   with:
  #     msrv: ${{ needs.msrv.outputs.msrv-version }}
